// ─────────────────────────────────────────────
// lib/mock-users.ts
// Typed mock data — replace with your API calls
// ─────────────────────────────────────────────

import { User } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "usr_001",
    name: "Amara Osei",
    email: "amara.osei@email.com",
    phone: "+1 (555) 234-5678",
    initials: "AO",
    roles: ["client", "provider"],
    status: "active",
    blockedRoles: [],
    joinedAt: "2023-04-12",
    lastActive: "2024-01-15",
    location: "Accra, Ghana",
    provider: {
      businessName: "Amara's Wellness Studio",
      category: "Health & Wellness",
      rating: 4.8,
      totalReviews: 142,
      verified: true,
      bio: "Certified wellness coach with 8+ years specializing in holistic healing and mindfulness practices.",
      services: [
        {
          id: "s1",
          name: "Wellness Consultation",
          price: 120,
          duration: "60 min",
          status: "active",
        },
        {
          id: "s2",
          name: "Group Meditation",
          price: 45,
          duration: "45 min",
          status: "active",
        },
        {
          id: "s3",
          name: "Nutrition Planning",
          price: 200,
          duration: "90 min",
          status: "paused",
        },
      ],
      businessHours: [
        { day: "Monday", open: "09:00", close: "17:00", available: true },
        { day: "Tuesday", open: "09:00", close: "17:00", available: true },
        { day: "Wednesday", open: "10:00", close: "18:00", available: true },
        { day: "Thursday", open: "09:00", close: "17:00", available: true },
        { day: "Friday", open: "09:00", close: "15:00", available: true },
        { day: "Saturday", open: "10:00", close: "13:00", available: true },
        { day: "Sunday", open: null, close: null, available: false },
      ],
    },
  },
  {
    id: "usr_002",
    name: "Marcus Webb",
    email: "marcus.webb@techsupplies.com",
    phone: "+1 (555) 876-5432",
    initials: "MW",
    roles: ["vendor", "employer"],
    status: "active",
    blockedRoles: [],
    joinedAt: "2022-11-08",
    lastActive: "2024-01-14",
    location: "Lagos, Nigeria",
    vendor: {
      storeName: "TechSupplies Pro",
      category: "Electronics",
      rating: 4.5,
      totalSales: 1284,
      verified: true,
      products: [
        {
          id: "p1",
          name: "Wireless Headphones X200",
          price: 89.99,
          stock: 45,
          status: "active",
        },
        {
          id: "p2",
          name: "USB-C Hub 7-in-1",
          price: 34.99,
          stock: 120,
          status: "active",
        },
        {
          id: "p3",
          name: "Laptop Stand Adjustable",
          price: 49.99,
          stock: 0,
          status: "out_of_stock",
        },
        {
          id: "p4",
          name: "Mechanical Keyboard TKL",
          price: 129.99,
          stock: 18,
          status: "active",
        },
      ],
    },
    employer: {
      companyName: "TechSupplies Pro Ltd.",
      industry: "Retail Technology",
      size: "11–50",
      openings: [
        {
          id: "j1",
          title: "Senior Sales Associate",
          type: "Full-time",
          location: "Lagos",
          status: "active",
          applicants: 23,
        },
        {
          id: "j2",
          title: "Warehouse Manager",
          type: "Full-time",
          location: "Lagos",
          status: "active",
          applicants: 11,
        },
        {
          id: "j3",
          title: "Customer Support Rep",
          type: "Part-time",
          location: "Remote",
          status: "closed",
          applicants: 54,
        },
      ],
    },
  },
  {
    id: "usr_003",
    name: "Sofia Reyes",
    email: "sofia.r@domain.com",
    phone: "+1 (555) 345-6789",
    initials: "SR",
    roles: ["client"],
    status: "active",
    blockedRoles: [],
    joinedAt: "2024-01-02",
    lastActive: "2024-01-15",
    location: "Nairobi, Kenya",
  },
  {
    id: "usr_004",
    name: "Daniel Kwame",
    email: "d.kwame@platform.com",
    phone: "+1 (555) 456-7890",
    initials: "DK",
    roles: ["admin"],
    status: "active",
    blockedRoles: [],
    joinedAt: "2022-03-15",
    lastActive: "2024-01-15",
    location: "Kumasi, Ghana",
  },
  {
    id: "usr_005",
    name: "Priya Nair",
    email: "priya.nair@wellness.io",
    phone: "+1 (555) 567-8901",
    initials: "PN",
    roles: ["provider", "staff"],
    status: "suspended",
    blockedRoles: ["staff"],
    joinedAt: "2023-07-22",
    lastActive: "2024-01-10",
    location: "Abuja, Nigeria",
    provider: {
      businessName: "Priya's Yoga & Wellness",
      category: "Fitness & Yoga",
      rating: 4.2,
      totalReviews: 67,
      verified: false,
      bio: "Certified yoga instructor focused on therapeutic yoga and stress management.",
      services: [
        {
          id: "s1",
          name: "Private Yoga Session",
          price: 80,
          duration: "60 min",
          status: "active",
        },
        {
          id: "s2",
          name: "Online Class",
          price: 25,
          duration: "45 min",
          status: "active",
        },
      ],
      businessHours: [
        { day: "Monday", open: "07:00", close: "19:00", available: true },
        { day: "Tuesday", open: "07:00", close: "19:00", available: true },
        { day: "Wednesday", open: "07:00", close: "19:00", available: true },
        { day: "Thursday", open: "07:00", close: "19:00", available: true },
        { day: "Friday", open: "07:00", close: "17:00", available: true },
        { day: "Saturday", open: "08:00", close: "14:00", available: true },
        { day: "Sunday", open: null, close: null, available: false },
      ],
    },
  },
  {
    id: "usr_006",
    name: "Kofi Mensah",
    email: "kofi@builds.gh",
    phone: "+1 (555) 678-9012",
    initials: "KM",
    roles: ["employer"],
    status: "active",
    blockedRoles: [],
    joinedAt: "2023-05-18",
    lastActive: "2024-01-13",
    location: "Accra, Ghana",
    employer: {
      companyName: "Builds Ghana Ltd",
      industry: "Construction",
      size: "51–200",
      openings: [
        {
          id: "j1",
          title: "Civil Engineer",
          type: "Full-time",
          location: "Accra",
          status: "active",
          applicants: 38,
        },
        {
          id: "j2",
          title: "Site Supervisor",
          type: "Contract",
          location: "Takoradi",
          status: "active",
          applicants: 15,
        },
      ],
    },
  },
];
