import type { Metadata } from "next";
import "./globals.css";
import { Bai_Jamjuree } from "next/font/google";
import Header from "@/components/localComponents/header";
import Footer from "@/components/localComponents/footer";
import { ThemeProvider } from "@/components/ui/themeProvider";
import Aurora from "@/components/Aurora";

// Load Bai Jamjuree font
const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${baiJamjuree.className} antialiased space-y-8 relative`}
      >
        <div className="absolute w-full h-[600px] -z-10 ">
          <Aurora
            colorStops={[
              "#00c06b", // deeper green
              "#56f09f", // primary light green
              "#8affc9", // neon mint glow
            ]}
            blend={1}
            amplitude={0.8}
            speed={0.5}
          />
        </div>
        <div className="p-4">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
