import type { Metadata } from "next";
import "./globals.css";
import { Bai_Jamjuree } from "next/font/google";
import Header, { BottomTabs } from "@/components/localComponents/header";
import Footer from "@/components/localComponents/footer";
import { ThemeProvider } from "@/components/ui/themeProvider";
import Aurora from "@/components/Aurora";

// Load Bai Jamjuree font
const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baiJamjuree.className} antialiased relative`}>
        <Header />
        {children}
        <Footer />
        <div className="fixed -bottom-1 w-full z-50 md:hidden">
          <BottomTabs />
        </div>
      </body>
    </html>
  );
}
